FROM php:7.4.3-fpm

RUN apt-get update
RUN apt-get install -y \
    build-essential libssl-dev libffi-dev libpq-dev libpng-dev libjpeg-dev libxml2-dev vim cron zip unzip p7zip-full
RUN docker-php-ext-install pdo pdo_mysql
RUN apt-get install zip unzip p7zip-full
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
