version: "3.7"
services:
  mongo1:
    image: mongo
    container_name: mongo1
    ports:
      - 31141:27017
    # expose: # 開給內網
    #     - 5000
    command: mongod --replSet RS --bind_ip_all --dbpath /data/db
    volumes:
      - ./data/mongo1:/data/db
  mongo2:
    image: mongo
    container_name: mongo2
    ports:
      - 31142:27017
    command: mongod --replSet RS --bind_ip_all --dbpath /data/db
    volumes:
      - ./data/mongo2:/data/db
  mongo3:
    image: mongo
    container_name: mongo3
    ports:
      - 31143:27017
    command: mongod --replSet RS --bind_ip_all --dbpath /data/db
    volumes:
      - ./data/mongo3:/data/db
