version: '3'
# 爬蟲 splash伺服器
services:
  scrapy:
    container_name: scrapy
    image: scrapinghub/splash
    ports:
      - 8050:8050
    volumes:
      - ../spiders:/usr/src/app
    command: ping 127.0.0.1 # 為了不讓他中止
