version: "3"

services:
  gitea:
    image: gitea/gitea:1.13.1
    container_name: gitea
    # environment:
    #   - USER_UID=1000
    #   - USER_GID=1000
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
      - "22:22"
